apiVersion: v1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alb-ingress
  namespace: web-public
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:564677439943:certificate/57deae4c-f6c3-4f3e-aaf0-185a71e7c5aa,arn:aws:acm:ap-northeast-1:564677439943:certificate/7c0f31ea-f980-4b4f-aca1-0ac9d73199f3,arn:aws:acm:ap-northeast-1:564677439943:certificate/293a2888-ff73-4f18-b06c-273350193b5f
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/security-groups: sg-07c805c0ad5e49e2e
    alb.ingress.kubernetes.io/subnets: subnet-70bbc92b,subnet-f45541dc,subnet-fa7f7fb3
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/healthy-threshold-count: '3'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
  labels:
    app: alb-ingress
spec:
  rules:
    - host: fascia.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: fascia-service
              servicePort: 80
    - host: whalebird.org
      http:
        paths:
          - path: /*
            backend:
              serviceName: whalebirdorg-service
              servicePort: 80
    - host: pleroma.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: pleromaio-service
              servicePort: 80
