apiVersion: v1
kind: ConfigMap
metadata:
  name: seiyuwatch-env
data:
  DB_HOST: nyaruko.cju8robzjmqc.ap-northeast-1.rds.amazonaws.com
  S3_BUCKET: seiyu-watch
  RELX_REPLACE_OS_VARS: "true"
  AWS_DEFAULT_REGION: ap-northeast-1
  OTEL_EXPORTER_ENDPOINT: "http://monitoring-jaeger.monitoring.svc.cluster.local:4318"
