apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-public

resources:
- external-secrets.yaml
- service.yaml
- target-group-binding.yaml
- deployment.yaml

images:
- name: nextjs
  newName: 564677439943.dkr.ecr.ap-northeast-1.amazonaws.com/h3poteto/whalebirdsocial
  newTag: sha-97d5c2637b90705051e1bdae846fedff0c088869
